name: Commit on GitHub
on:
    push:
        branches:
          - main
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Make new a .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_PORT: 3000
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_DB: "ci-test"
          envkey_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/ci-test"
          directory: .
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node npm run test